apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.5.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: kube-prometheus-stack

    prometheus:
      prometheusSpec:
        retention: 7d

    grafana:
      adminUser: admin
      adminPassword: admin
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.logging.svc.cluster.local
          isDefault: false
          jsonData:
            maxLines: 1000
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - grafana.cachefly.site
        tls:
          - hosts:
              - grafana.cachefly.site
            secretName: grafana-tls
