apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.5.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: kube-prometheus-stack

    prometheus:
      prometheusSpec:
        retention: 7d

    # Alertmanager configuration
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
        secrets:
          - alertmanager-telegram
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['alertname', 'severity', 'service']
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 4h
          receiver: 'telegram'
          routes:
            - match:
                severity: critical
              receiver: 'telegram'
              repeat_interval: 1h
            - match:
                severity: warning
              receiver: 'telegram'
              repeat_interval: 4h
            - match:
                severity: info
              receiver: 'telegram'
              repeat_interval: 12h
        receivers:
          - name: 'telegram'
            telegram_configs:
              - bot_token_file: /etc/alertmanager/secrets/alertmanager-telegram/bot-token
                chat_id: 541762988
                parse_mode: 'HTML'
                message: |
                  <b>🔔 {{ .Status | toUpper }}</b>
                  {{ range .Alerts }}
                  <b>Alert:</b> {{ .Labels.alertname }}
                  <b>Severity:</b> {{ .Labels.severity }}
                  <b>Service:</b> {{ .Labels.service }}
                  <b>Summary:</b> {{ .Annotations.summary }}
                  <b>Description:</b> {{ .Annotations.description }}
                  {{ end }}

    grafana:
      adminUser: admin
      adminPassword: admin

      # Datasources configuration
      additionalDataSources:
        - name: Loki
          type: loki
          uid: loki
          access: proxy
          url: http://loki-gateway.logging.svc.cluster.local
          isDefault: false
          jsonData:
            maxLines: 5000
            timeout: 60

      # Datasource for Prometheus (auto-configured by kube-prometheus-stack)
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              uid: prometheus
              url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
              access: proxy
              isDefault: true
              jsonData:
                timeInterval: 30s

      # Dashboard providers - enables auto-loading dashboards from ConfigMaps
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
            - name: 'kubernetes'
              orgId: 1
              folder: 'Kubernetes'
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/kubernetes

      # Pre-load community dashboards by ID from grafana.com
      dashboards:
        kubernetes:
          # Kubernetes Cluster Monitoring (via Prometheus)
          k8s-cluster:
            gnetId: 7249
            revision: 1
            datasource: Prometheus
          # Kubernetes Deployment Statefulset Daemonset metrics
          k8s-deployments:
            gnetId: 8588
            revision: 1
            datasource: Prometheus
          # Node Exporter Full
          node-exporter:
            gnetId: 1860
            revision: 31
            datasource: Prometheus
          # Loki Dashboard for Loki metrics
          loki-metrics:
            gnetId: 13639
            revision: 2
            datasource: Prometheus

      # Sidecar to auto-load dashboards from ConfigMaps
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          folder: /tmp/dashboards
          searchNamespace: monitoring
          provider:
            foldersFromFilesStructure: true

      # Ingress configuration
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - grafana.cachefly.site
        tls:
          - hosts:
              - grafana.cachefly.site
            secretName: grafana-tls

      # Enable persistence for dashboards
      persistence:
        enabled: true
        size: 1Gi
