# ADHD App Secrets (SealedSecret)
#
# To create/update this sealed secret:
# 1. Create a regular secret YAML file (DO NOT commit this):
#    kubectl create secret generic adhd-secrets \
#      --namespace=adhd \
#      --from-literal=MONGODB_URI="mongodb://adhd_user:PASSWORD@HOST:27017/mywebadhd?authSource=mywebadhd" \
#      --from-literal=NEXT_PUBLIC_SITE_URL="https://www.cachefly.site" \
#      --from-literal=CLAUDE_API_KEY="your-key-here" \
#      --dry-run=client -o yaml > /tmp/adhd-secrets.yaml
#
# 2. Seal the secret:
#    kubeseal --format=yaml --cert=pub-sealed-secrets.pem \
#      < /tmp/adhd-secrets.yaml > apps/adhd-app/sealed-secret.yaml
#
# 3. Delete the plaintext file:
#    rm /tmp/adhd-secrets.yaml
#
# 4. Commit the sealed secret to Git

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adhd-secrets
  namespace: adhd
spec:
  encryptedData:
    # PLACEHOLDER - Replace with actual sealed values
    # Generate using kubeseal command above
    MONGODB_URI: REPLACE_WITH_SEALED_VALUE
    NEXT_PUBLIC_SITE_URL: REPLACE_WITH_SEALED_VALUE
    CLAUDE_API_KEY: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: adhd-secrets
      namespace: adhd
    type: Opaque
