apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lingualink-backend-netpol
  namespace: lingua-app
spec:
  podSelector:
    matchLabels:
      app: lingualink-backend
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from ingress controller (for API requests)
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000

    # Allow traffic from Prometheus (for metrics scraping)
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 8000

    # Allow traffic from within the same namespace (for internal communication)
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
---
# Egress policy - allow DNS and database
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lingualink-backend-egress
  namespace: lingua-app
spec:
  podSelector:
    matchLabels:
      app: lingualink-backend
  policyTypes:
    - Egress
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Allow PostgreSQL
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432

    # Allow HTTPS for external APIs (Telegram)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
