apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lingualink-backend-netpol
  namespace: lingua-app
spec:
  podSelector:
    matchLabels:
      app: lingualink-backend
  policyTypes:
    - Ingress
  ingress:
    # 1) Allow traffic from ingress-nginx (incoming HTTP traffic from outside)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000

    # 2) Allow traffic from Prometheus (scrape /metrics)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 8000

    # 3) Allow traffic from pods within the same namespace (internal calls)
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
---
# Egress policy - allow DNS, PostgreSQL и HTTPS наружу
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lingualink-backend-egress
  namespace: lingua-app
spec:
  podSelector:
    matchLabels:
      app: lingualink-backend
  policyTypes:
    - Egress
  egress:
    # 1) Allow DNS (CoreDNS in kube-system)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # 2) Allow PostgreSQL (statefulset postgres in lingua-app)
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432

    # 3) Allow outgoing HTTPS (Telegram, external APIs)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
