# ⚠️ DO NOT COMMIT THIS FILE WITH REAL CREDENTIALS ⚠️
#
# This is a template for creating the SealedSecret.
# Follow these steps to generate the encrypted SealedSecret:
#
# 1. Get PostgreSQL password from the existing postgres-secret:
#    kubectl get secret postgres-secret -n lingua-app -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 -d
#
# 2. Generate a strong API key for admin endpoints:
#    openssl rand -hex 32
#
# 3. Generate a strong Telegram webhook secret:
#    openssl rand -hex 32
#
# 4. Create a temporary secret file (replace placeholders):
#    cat <<EOF > /tmp/backend-secret.yaml
#    apiVersion: v1
#    kind: Secret
#    metadata:
#      name: lingualink-backend-secret
#      namespace: lingua-app
#    type: Opaque
#    stringData:
#      # Database connection (replace <PASSWORD> with actual postgres password)
#      DATABASE_URL: "postgresql+asyncpg://lingualink:<PASSWORD>@postgres.lingua-app.svc.cluster.local:5432/lingualink"
#
#      # Telegram bot token (get from @BotFather)
#      TELEGRAM_BOT_TOKEN: "<YOUR_TELEGRAM_BOT_TOKEN>"
#
#      # Telegram webhook secret (generated above)
#      TELEGRAM_WEBHOOK_SECRET: "<GENERATED_WEBHOOK_SECRET>"
#
#      # API key for admin endpoints (generated above)
#      API_KEY: "<GENERATED_API_KEY>"
#    EOF
#
# 5. Generate SealedSecret:
#    kubeseal --format yaml \
#      --controller-name=sealed-secrets \
#      --controller-namespace=sealed-secrets \
#      < /tmp/backend-secret.yaml \
#      > apps/lingua-app/backend/sealed-secret.yaml
#
# 6. Clean up temporary file:
#    rm /tmp/backend-secret.yaml
#
# 7. Commit and push the sealed-secret.yaml file
#
# Security Notes:
# - DATABASE_URL: Use the same password as postgres-secret
# - TELEGRAM_WEBHOOK_SECRET: Used to verify Telegram webhook requests
# - API_KEY: Required for all /api/admin/* endpoints
# - Never commit unencrypted secrets to git

apiVersion: v1
kind: Secret
metadata:
  name: lingualink-backend-secret
  namespace: lingua-app
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_WITH_ACTUAL_URL"
  TELEGRAM_BOT_TOKEN: "REPLACE_WITH_BOT_TOKEN"
  TELEGRAM_WEBHOOK_SECRET: "REPLACE_WITH_WEBHOOK_SECRET"
  API_KEY: "REPLACE_WITH_API_KEY"
