apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: promtail
      version: 6.16.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: loki
  values:
    config:
      clients:
        - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

      snippets:
        pipelineStages:
          - cri: {}
          - labeldrop:
              - filename
          - timestamp:
              source: time
              format: RFC3339Nano

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

    # Tolerations to run on all nodes
    tolerations:
      - effect: NoSchedule
        operator: Exists

    # Service monitor for Prometheus integration
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
