# Template for creating PostgreSQL secret
# DO NOT commit this file with actual credentials!
# Use this to create a SealedSecret:
#
# 1. Create secret with real values:
#    kubectl create secret generic postgres-secret \
#      --namespace=lingua-app \
#      --from-literal=POSTGRES_PASSWORD=<your-password> \
#      --dry-run=client -o yaml > secret.yaml
#
# 2. Seal the secret:
#    kubeseal --format=yaml --cert=pub-sealed-secrets.pem \
#      < secret.yaml > sealed-secret.yaml
#
# 3. Delete the plaintext secret file:
#    rm secret.yaml
#
# 4. Commit sealed-secret.yaml to git
#
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lingua-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: CHANGE_THIS_PASSWORD
  # DATA_SOURCE_URI for postgres_exporter
  # Format: postgresql://user:password@host:port/database?sslmode=disable
  DATA_SOURCE_URI: postgresql://lingualink:CHANGE_THIS_PASSWORD@localhost:5432/lingualink?sslmode=disable
